[2024-12-30 11:37:51,443] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_V1.first_task manual__2024-12-30T11:37:50.889923+00:00 [queued]>
[2024-12-30 11:37:51,454] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_V1.first_task manual__2024-12-30T11:37:50.889923+00:00 [queued]>
[2024-12-30 11:37:51,454] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 11:37:51,454] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2024-12-30 11:37:51,454] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 11:37:51,463] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): first_task> on 2024-12-30 11:37:50.889923+00:00
[2024-12-30 11:37:51,469] {standard_task_runner.py:52} INFO - Started process 11141 to run task
[2024-12-30 11:37:51,472] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_V1', 'first_task', 'manual__2024-12-30T11:37:50.889923+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp15suh01e', '--error-file', '/tmp/tmp2f2sro9w']
[2024-12-30 11:37:51,472] {standard_task_runner.py:80} INFO - Job 5: Subtask first_task
[2024-12-30 11:37:51,509] {task_command.py:370} INFO - Running <TaskInstance: first_dag_V1.first_task manual__2024-12-30T11:37:50.889923+00:00 [running]> on host 0766066e7c2f
[2024-12-30 11:37:51,564] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=swetansu
AIRFLOW_CTX_DAG_ID=first_dag_V1
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-30T11:37:50.889923+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-30T11:37:50.889923+00:00
[2024-12-30 11:37:51,565] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-30 11:37:51,566] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'i am task1']
[2024-12-30 11:37:51,575] {subprocess.py:85} INFO - Output:
[2024-12-30 11:37:51,579] {subprocess.py:92} INFO - bash: line 1: i: command not found
[2024-12-30 11:37:51,579] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-30 11:37:51,591] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-30 11:37:51,593] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_V1, task_id=first_task, execution_date=20241230T113750, start_date=20241230T113751, end_date=20241230T113751
[2024-12-30 11:37:51,603] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 11141)
[2024-12-30 11:37:51,643] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-30 11:37:51,682] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
