[2024-12-30 11:38:36,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_V1.first_task manual__2024-12-30T11:38:35.778493+00:00 [queued]>
[2024-12-30 11:38:36,057] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_V1.first_task manual__2024-12-30T11:38:35.778493+00:00 [queued]>
[2024-12-30 11:38:36,057] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 11:38:36,057] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2024-12-30 11:38:36,057] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 11:38:36,069] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): first_task> on 2024-12-30 11:38:35.778493+00:00
[2024-12-30 11:38:36,074] {standard_task_runner.py:52} INFO - Started process 11190 to run task
[2024-12-30 11:38:36,076] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_V1', 'first_task', 'manual__2024-12-30T11:38:35.778493+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpnaklnopa', '--error-file', '/tmp/tmpeojcd2ed']
[2024-12-30 11:38:36,077] {standard_task_runner.py:80} INFO - Job 6: Subtask first_task
[2024-12-30 11:38:36,129] {task_command.py:370} INFO - Running <TaskInstance: first_dag_V1.first_task manual__2024-12-30T11:38:35.778493+00:00 [running]> on host 0766066e7c2f
[2024-12-30 11:38:36,215] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=swetansu
AIRFLOW_CTX_DAG_ID=first_dag_V1
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-30T11:38:35.778493+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-30T11:38:35.778493+00:00
[2024-12-30 11:38:36,216] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-30 11:38:36,217] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'i am task1']
[2024-12-30 11:38:36,238] {subprocess.py:85} INFO - Output:
[2024-12-30 11:38:36,238] {subprocess.py:92} INFO - bash: line 1: i: command not found
[2024-12-30 11:38:36,239] {subprocess.py:96} INFO - Command exited with return code 127
[2024-12-30 11:38:36,254] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-30 11:38:36,258] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_V1, task_id=first_task, execution_date=20241230T113835, start_date=20241230T113836, end_date=20241230T113836
[2024-12-30 11:38:36,276] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 11190)
[2024-12-30 11:38:36,288] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-30 11:38:36,327] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
